; Sound effect data generated by Musetracker

MUSE_L9:
  .byte 153
  .byte 204
  .byte 124
  .byte 144
  .byte 231
  .byte 204
  .byte 132
  .byte 207
  .byte 204
  .byte 139
  .byte 207
  .byte 204
  .byte 148
  .byte 207
  .byte 204
  .byte 157
  .byte 207
  .byte 204
  .byte 166
  .byte 225
  .byte 206
  .word MUSE_L9 + 0
