; Song data generated by Musetracker

MUSE_L2:
  .byte 0
  .word MUSE_L10
  .word MUSE_L11
  .word MUSE_L12
  .word MUSE_L13
  .word MUSE_L14
  .word MUSE_L15
  .word MUSE_L16
  .word MUSE_L17
  .word MUSE_L18
  .word MUSE_L19
  .word MUSE_L20
  .word MUSE_L21

MUSE_L12:
  .byte 0, $FF

MUSE_L14:
  .byte 0, $FF

MUSE_L16:
  .byte 0, $FF

MUSE_L18:
  .byte 0, $FF

MUSE_L20:
  .byte 0, $FF

MUSE_L13:
  .word MUSE_L22

MUSE_L15:
  .word MUSE_L23

MUSE_L17:
  .word MUSE_L24

MUSE_L19:
  .word MUSE_L25

MUSE_L21:
  .word MUSE_L26

MUSE_L22:
  .byte 128
  .byte 81
  .byte 207
  .byte 12
  .byte 84
  .byte 6
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 12
  .byte 89
  .byte 12
  .byte 86
  .byte 12
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 18
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 84
  .byte 207
  .byte 6
  .byte 81
  .byte 12
  .byte 84
  .byte 6
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 12
  .byte 89
  .byte 12
  .byte 86
  .byte 12
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 18
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 84
  .byte 207
  .byte 6
  .byte 81
  .byte 12
  .byte 84
  .byte 6
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 12
  .byte 89
  .byte 12
  .byte 86
  .byte 12
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 18
  .byte 226, 2
  .byte 129
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 84
  .byte 207
  .byte 6
  .byte 81
  .byte 12
  .byte 84
  .byte 6
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 12
  .byte 89
  .byte 12
  .byte 86
  .byte 12
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 86
  .byte 207
  .byte 18
  .byte 226, 2
  .byte 130
  .byte 110
  .byte 6
  .byte 227
  .byte 128
  .byte 84
  .byte 207
  .byte 6
  .byte 215

MUSE_L23:
  .byte 223, 162
  .byte 131
  .byte 117
  .byte 207
  .byte 12
  .byte 224
  .byte 214
  .byte 6
  .byte 223, 162
  .byte 117
  .byte 207
  .byte 18
  .byte 226, 1
  .byte 206
  .byte 6
  .byte 226, 2
  .byte 6
  .byte 227
  .byte 132
  .byte 117
  .byte 207
  .byte 12
  .byte 224
  .byte 214
  .byte 6
  .byte 223, 162
  .byte 117
  .byte 207
  .byte 6
  .byte 224
  .byte 131
  .byte 117
  .byte 6
  .byte 214
  .byte 6
  .byte 120
  .byte 207
  .byte 6
  .byte 223, 162
  .byte 119
  .byte 12
  .byte 226, 1
  .byte 206
  .byte 6
  .byte 227
  .byte 115
  .byte 207
  .byte 12
  .byte 224
  .byte 214
  .byte 6
  .byte 223, 162
  .byte 132
  .byte 119
  .byte 207
  .byte 12
  .byte 226, 1
  .byte 206
  .byte 6
  .byte 227
  .byte 115
  .byte 207
  .byte 12
  .byte 224
  .byte 214
  .byte 6
  .byte 214
  .byte 6
  .byte 226, 2
  .byte 131
  .byte 116
  .byte 207
  .byte 6
  .byte 115
  .byte 207
  .byte 6
  .byte 113
  .byte 207
  .byte 6
  .byte 227
  .byte 223, 162
  .byte 110
  .byte 207
  .byte 12
  .byte 224
  .byte 214
  .byte 6
  .byte 223, 162
  .byte 110
  .byte 207
  .byte 18
  .byte 226, 1
  .byte 206
  .byte 6
  .byte 226, 2
  .byte 12
  .byte 217, 12
  .byte 227
  .byte 224
  .byte 132
  .byte 105
  .byte 207
  .byte 6
  .byte 107
  .byte 6
  .byte 108
  .byte 6
  .byte 115
  .byte 6
  .byte 218
  .byte 131
  .byte 110
  .byte 12
  .byte 108
  .byte 6
  .byte 107
  .byte 18
  .byte 219, 32
  .byte 8
  .byte 222, 44
  .byte 4
  .byte 223, 162
  .byte 107
  .byte 12
  .byte 219, 32
  .byte 224
  .byte 8
  .byte 222, 44
  .byte 4
  .byte 223, 162
  .byte 107
  .byte 12
  .byte 219, 32
  .byte 224
  .byte 8
  .byte 222, 44
  .byte 4
  .byte 110
  .byte 8
  .byte 113
  .byte 8
  .byte 115
  .byte 8
  .byte 215

MUSE_L24:
  .byte 134
  .byte 81
  .byte 207
  .byte 12
  .byte 133
  .byte 84
  .byte 6
  .byte 214
  .byte 6
  .byte 134
  .byte 86
  .byte 207
  .byte 12
  .byte 133
  .byte 89
  .byte 12
  .byte 134
  .byte 86
  .byte 12
  .byte 214
  .byte 6
  .byte 133
  .byte 86
  .byte 207
  .byte 6
  .byte 134
  .byte 86
  .byte 18
  .byte 133
  .byte 84
  .byte 6
  .byte 134
  .byte 81
  .byte 12
  .byte 133
  .byte 84
  .byte 6
  .byte 214
  .byte 6
  .byte 134
  .byte 86
  .byte 207
  .byte 12
  .byte 133
  .byte 89
  .byte 12
  .byte 134
  .byte 86
  .byte 12
  .byte 214
  .byte 6
  .byte 133
  .byte 86
  .byte 207
  .byte 6
  .byte 134
  .byte 86
  .byte 18
  .byte 133
  .byte 84
  .byte 6
  .byte 134
  .byte 81
  .byte 12
  .byte 133
  .byte 84
  .byte 6
  .byte 214
  .byte 6
  .byte 134
  .byte 86
  .byte 207
  .byte 12
  .byte 133
  .byte 89
  .byte 12
  .byte 134
  .byte 86
  .byte 12
  .byte 214
  .byte 6
  .byte 133
  .byte 86
  .byte 207
  .byte 6
  .byte 134
  .byte 86
  .byte 18
  .byte 133
  .byte 84
  .byte 6
  .byte 134
  .byte 81
  .byte 12
  .byte 133
  .byte 84
  .byte 6
  .byte 214
  .byte 6
  .byte 134
  .byte 86
  .byte 207
  .byte 12
  .byte 133
  .byte 89
  .byte 12
  .byte 134
  .byte 86
  .byte 12
  .byte 214
  .byte 6
  .byte 133
  .byte 86
  .byte 207
  .byte 6
  .byte 134
  .byte 86
  .byte 18
  .byte 133
  .byte 84
  .byte 6
  .byte 215

MUSE_L25:
  .byte 135
  .byte 77
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 137
  .byte 110
  .byte 3
  .byte 214
  .byte 3
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 3
  .byte 135
  .byte 89
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 138
  .byte 110
  .byte 12
  .byte 135
  .byte 89
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 137
  .byte 110
  .byte 3
  .byte 214
  .byte 3
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 3
  .byte 135
  .byte 89
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 138
  .byte 110
  .byte 6
  .byte 136
  .byte 96
  .byte 198
  .byte 6
  .byte 135
  .byte 77
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 137
  .byte 110
  .byte 3
  .byte 214
  .byte 3
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 3
  .byte 135
  .byte 89
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 138
  .byte 110
  .byte 12
  .byte 135
  .byte 89
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 137
  .byte 110
  .byte 3
  .byte 214
  .byte 3
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 3
  .byte 135
  .byte 89
  .byte 207
  .byte 4
  .byte 214
  .byte 8
  .byte 137
  .byte 110
  .byte 207
  .byte 3
  .byte 214
  .byte 9
  .byte 136
  .byte 96
  .byte 207
  .byte 12
  .byte 138
  .byte 110
  .byte 6
  .byte 136
  .byte 96
  .byte 198
  .byte 6
  .byte 215

MUSE_L26:
  .byte 0
  .byte 128, 128
  .byte 129

