; Sound effect data generated by Musetracker

MUSE_L6:
  .byte 111
  .byte 203
  .byte 209
  .byte 136
  .byte 207
  .byte 109
  .byte 207
  .byte 106
  .byte 208
  .byte 111
  .byte 203
  .byte 104
  .byte 207
  .byte 109
  .byte 207
  .byte 106
  .byte 208
  .byte 96
  .byte 208
  .byte 101
  .byte 203
  .byte 104
  .byte 136
  .byte 207
  .byte 99
  .byte 207
  .byte 205
